#!/bin/sh
set -e

FILE="/usr/share/nginx/html/index.html"
TMP="/tmp/index-agendaos-plans.html"

awk '
BEGIN { skip=0 }
/<section id="planes"/ {
  print "    <section id=\"planes\" class=\"px-4 py-16 sm:px-6 lg:py-24\"><div class=\"mx-auto max-w-7xl\"><div class=\"mb-14 text-center\"><p class=\"text-sm font-black uppercase tracking-[0.28em] text-sky-300\">Planes AgendaOS</p><h2 class=\"mt-5 text-4xl font-black sm:text-5xl\">Una plataforma inteligente para vender, organizar y automatizar.</h2><p class=\"mx-auto mt-6 max-w-3xl text-lg leading-9 text-white/55\">Elige el nivel de operación que necesita tu negocio: presencia premium, sistema conectado o automatización total con IA integrada.</p></div><div class=\"grid gap-6 lg:grid-cols-3\">"
  print "<div class=\"glass card-hover rounded-[2.5rem] p-8\"><p class=\"text-sm font-black uppercase tracking-[0.22em] text-sky-300\">Landing Premium</p><h3 class=\"mt-4 text-3xl font-black\">Agenda Web</h3><p class=\"mt-3 text-xl font-black leading-tight text-white\">Tu negocio online listo para recibir reservas.</p><p class=\"mt-5 text-sm leading-7 text-white/65\">Landing page moderna diseñada para convertir visitas en clientes mediante reservas rápidas y contacto directo con el negocio.</p><p class=\"mt-8\"><span class=\"text-2xl font-black text-white/25 line-through\">$230.000</span> <span class=\"ml-3 text-5xl font-black\">$149.000</span></p><p class=\"mt-3 text-sm text-white/45\">Pago único de implementación.</p><p class=\"mt-1 text-xs text-white/30\">No incluye dominio.</p><ul class=\"mt-8 space-y-3 text-sm text-white/75\"><li>✨ Diseño premium personalizado</li><li>✨ Reservas online simples</li><li>✨ Botón directo a WhatsApp</li><li>✨ Optimizado para móviles</li><li>✨ Experiencia rápida y moderna</li><li>✨ Servicios y horarios visibles</li><li>✨ Integración directa con el negocio</li></ul><div class=\"mt-8 rounded-2xl border border-sky-300/15 bg-sky-400/10 p-4 text-xs font-semibold leading-6 text-cyan-200\">No incluye sistema administrativo ni agente inteligente sofIA.</div><a href=\"https://wa.me/56973675754\" target=\"_blank\" class=\"mt-8 inline-flex w-full justify-center rounded-full bg-white px-6 py-4 text-sm font-black text-slate-950\">Solicitar Agenda Web</a></div>"
  print "<div class=\"card-hover rounded-[2.5rem] border border-sky-300/40 bg-sky-400/[0.10] p-8 shadow-[0_0_50px_rgba(56,189,248,.18)]\"><span class=\"rounded-full bg-sky-400 px-4 py-2 text-xs font-black text-slate-950\">Sistema Integrado</span><h3 class=\"mt-6 text-3xl font-black\">Agenda Business</h3><p class=\"mt-3 text-xl font-black leading-tight text-white\">Reservas, control y operación desde un solo lugar.</p><p class=\"mt-5 text-sm leading-7 text-white/65\">Landing inteligente conectada a un sistema de gestión para administrar reservas, servicios, profesionales y operación diaria.</p><p class=\"mt-8\"><span class=\"text-2xl font-black text-white/25 line-through\">$370.000</span> <span class=\"ml-3 text-5xl font-black\">$199.000</span></p><p class=\"mt-3 text-lg font-black text-cyan-300\">+ $35.000 / mes</p><p class=\"text-sm text-white/45\">Incluye mantenimiento y mejoras.</p><ul class=\"mt-8 space-y-3 text-sm text-white/75\"><li>✨ Todo lo incluido en Agenda Web</li><li>✨ Dashboard administrativo</li><li>✨ Sistema conectado a la landing</li><li>✨ Gestión de profesionales</li><li>✨ Servicios y productos</li><li>✨ Disponibilidad real</li><li>✨ Control de reservas</li><li>✨ Control de ventas</li><li>✨ Ingresos y egresos</li><li>✨ Reportes diarios, semanales y mensuales</li><li>✨ Métricas operativas</li><li>✨ Organización centralizada</li></ul><a href=\"https://wa.me/56973675754\" target=\"_blank\" class=\"mt-8 inline-flex w-full justify-center rounded-full bg-white px-6 py-4 text-sm font-black text-slate-950\">Solicitar Agenda Business</a></div>"
  print "<div class=\"glass card-hover rounded-[2.5rem] border border-cyan-300/30 p-8\"><p class=\"text-sm font-black uppercase tracking-[0.22em] text-cyan-300\">IA + Automatización Total</p><h3 class=\"mt-4 text-3xl font-black\">AgendaOS AI</h3><p class=\"mt-3 text-xl font-black leading-tight text-white\">El negocio funcionando automáticamente en tiempo real.</p><p class=\"mt-5 text-sm leading-7 text-white/65\">Landing, sistema y sofIA trabajando juntos en una plataforma completamente conectada.</p><p class=\"mt-8\"><span class=\"text-2xl font-black text-white/25 line-through\">$690.000</span> <span class=\"ml-3 text-5xl font-black\">$399.000</span></p><p class=\"mt-3 text-lg font-black text-cyan-300\">+ $65.000 / mes</p><p class=\"text-sm text-white/45\">Incluye mantenimiento, mejoras y soporte.</p><ul class=\"mt-8 space-y-3 text-sm text-white/75\"><li>✨ Todo lo incluido en Agenda Business</li><li>✨ sofIA integrada</li><li>✨ Responde mensajes automáticamente</li><li>✨ Soporte texto, voz e imágenes</li><li>✨ Agenda citas automáticamente</li><li>✨ Disponibilidad sincronizada en tiempo real</li><li>✨ Responde dudas del negocio</li><li>✨ Recomienda productos y servicios</li><li>✨ Comparte horarios e información</li><li>✨ Comparte catálogo</li><li>✨ Atención automatizada 24/7</li><li>✨ Integración completa con el sistema</li></ul><a href=\"https://wa.me/56973675754\" target=\"_blank\" class=\"mt-8 inline-flex w-full justify-center rounded-full bg-white px-6 py-4 text-sm font-black text-slate-950\">Solicitar AgendaOS AI</a></div>"
  print "</div></div></section>"
  print "    <section class=\"px-4 py-16 sm:px-6 lg:py-24\"><div class=\"card-hover mx-auto max-w-7xl overflow-hidden rounded-[2rem] border border-cyan-300/20 bg-gradient-to-br from-cyan-300/10 via-[#07111f] to-sky-500/10 p-6 sm:rounded-[3rem] lg:p-14\"><div class=\"grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center\"><div><div class=\"inline-flex rounded-full border border-cyan-300/20 bg-cyan-300/10 px-5 py-3 text-sm font-black text-cyan-200\">🚀 PRUEBA GRATIS 30 DÍAS</div><h2 class=\"mt-6 max-w-3xl text-4xl font-black sm:text-5xl\">Registra tu <span class=\"text-sky-300\">negocio</span> y empieza a usar Agenda<span class=\"text-sky-300\">OS</span>.</h2><p class=\"mt-6 max-w-2xl text-lg leading-9 text-white/60\">Crea tu cuenta, registra los datos del negocio y prueba el sistema base durante 30 días. Después puedes activar WhatsApp, página, agenda avanzada y automatización con sofIA según el plan que elijas.</p></div><div class=\"rounded-[2rem] border border-sky-300/15 bg-[#061524]/70 p-6 text-center\"><p class=\"text-sm font-black uppercase tracking-[0.22em] text-cyan-300\">Prueba para negocios</p><p class=\"mt-5 text-6xl font-black\">30 DÍAS</p><p class=\"mt-4 text-sm leading-7 text-white/55\">Sin compromiso inicial. Ideal para conocer el sistema, registrar tu negocio y validar si AgendaOS se adapta a tu operación.</p><a href=\"/registro.html\" class=\"mt-8 inline-flex w-full justify-center rounded-full bg-sky-400 px-6 py-4 text-sm font-black text-slate-950\">Empezar prueba gratis</a></div></div></div></section>"
  skip=1
  next
}
skip && /<\/main>/ { print; skip=0; next }
skip { next }
{ print }
' "$FILE" > "$TMP"

mv "$TMP" "$FILE"
nginx -s reload

echo "AgendaOS actualizado: planes nuevos + prueba gratis 30 días."
